### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by AchmadFathoni** [Egoistically/ALAuto#104]
```
[2020-03-19 01:53:24] Initializing config module
[2020-03-19 01:53:24] Validating config
[2020-03-19 01:53:24] Starting ALAuto!
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
[2020-03-19 01:53:29] Successfully connected to the service.
Traceback (most recent call last):
  File ".\ALAuto.py", line 191, in <module>
    output = Adb.exec_out('wm size').decode('utf-8').strip()
  File "C:\Users\acer\Downloads\Documents\Source_code\ALAuto\util\adb.py", line 78, in exec_out   
    process = subprocess.Popen(cmd, stdout = subprocess.PIPE)
  File "C:\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:\Python37\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
```
Python version : 3.7.4
ALauto Version : 5902a84fcf06e64ef1b00f3f3f1817d9240b6b50

**Comment by AchmadFathoni** [comment]
https://github.com/Egoistically/ALAuto/blob/5902a84fcf06e64ef1b00f3f3f1817d9240b6b50/util/adb.py#L77

`Adb.transID` is None when printed.

**Comment by AchmadFathoni** [comment]
Going deeper, `adb devices -l` command return 
```
List of devices attached
127.0.0.1:62001        device product:LGM-V300K model:LGM_V300K device:shamu
```
Start from 92656e2c6678e366873d3c42f4b8ca62a463d6a0 ALAuto looking for `transport_id` parameter, which is doesn't exist in ADB version 36 from Nox emulator that I use. @phantasmalmira what ADB version do you use?
