### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ramos852** [Egoistically/ALAuto#117]
Every time I run the bot with the specified command in the instructions I get this error log:
Traceback (most recent call last):
  File "ALAuto.py", line 5, in <module>
    from modules.combat import CombatModule
  File "C:\Users\nickr\ALAuto\modules\combat.py", line 5, in <module>
    from util.utils import Region, Utils
  File "C:\Users\nickr\ALAuto\util\utils.py", line 8, in <module>
    from scipy import spatial
  File "C:\Users\nickr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\spatial\__init__.py", line 96, in <module>
    from .qhull import *
ImportError: DLL load failed: The specified module could not be found.

Is this a known issue? I'm new to Python/ADB stuff so I would appreciate any help you could offer :D

**Comment by The1Percent** [comment]
Did you install from the requirements file?  It is possible you have some versioning issues.

**Comment by ramos852** [comment]
I tried to install the specific versions from the requirements file and my CLI returns a statement saying  "Requirement is already satisfied: C:\Users\nickr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages" for each component of the requirements file.

**Comment by hjk22** [comment]
If uninstalling and then reinstalling doesn't work, you're probably missing some visual c++ redist.
Check out this issue #87 .
