### ISSUE TITLE
KeyError: 'oil_limit'

### ISSUE THREAD

**Issue by AchmadFathoni** [Egoistically/ALAuto#15]
```
[2019-10-31 13:42:06] Initializing config module
[2019-10-31 13:42:06] Validating config
[2019-10-31 13:42:06] Starting ALAuto!
* daemon not running; starting now at tcp:5037
* daemon started successfully
[2019-10-31 13:42:12] Successfully connected to the service.
Traceback (most recent call last):
  File "ALAuto.py", line 188, in <module>
    if script.should_sortie():
  File "ALAuto.py", line 64, in should_sortie
    Utils.check_oil(self.config.combat['oil_limit'])
KeyError: 'oil_limit'1
```

`KeyError` is logic error means the ``oil_limit`` key doesn't exist.  I already use Nox, 1920x1080 resolution, and ADB connection is fine.

My config.ini

```
[Network]
Service: 127.0.0.1:62001

[Updates]
Enabled: True
Channel: Development

[Combat]
Enabled: False
Map: 3-4
OilLimit: 1000
RetireCycle: 2

[Modules]
Commissions: False
Enhancement: False
Missions: False
Retirement: False

[Events]
Enabled: False
Event: Crosswave
Levels: EX,H,N,E
```

**Comment by Egoistically** [comment]
Every single module (including combat) is disabled on your config.

**Comment by Egoistically** [comment]
Added extra checks on the [latest update](https://github.com/Egoistically/ALAuto/commit/80a960f7df5ff5a4c468cb24a390d2889715b1a0) so this doesn't happen again. Thanks.
