### ISSUE TITLE
Suck at result screen

### ISSUE THREAD

**Issue by wamakima5004** [Egoistically/ALAuto#16]
When I run this script, the script would be stuck at the second result screen. First one is result screen shows you got S and 3 stars, second is the one that shows the exp and mvp of the shipgirls. The script would click once and stop there. I let it hang for 20 mins just in case. If I manually click pass the result screen, the script would keep going with "combat ended". Below is the feedback when I ctrl+c.

`Traceback (most recent call last):

  File "ALAuto.py", line 191, in <module>
    script.run_sortie_cycle()
  File "ALAuto.py", line 72, in run_sortie_cycle
    self.run_combat_cycle()
  File "ALAuto.py", line 80, in run_combat_cycle
    result = self.modules['combat'].combat_logic_wrapper()
  File "E:\Downloads\ALAuto-master\modules\combat.py", line 76, in combat_logic_wrapper
    if not self.clear_map():
  File "E:\Downloads\ALAuto-master\modules\combat.py", line 364, in clear_map
    self.battle_handler()
  File "E:\Downloads\ALAuto-master\modules\combat.py", line 170, in battle_handler
    if Utils.find("menu/drop_ssr"):
  File "E:\Downloads\ALAuto-master\util\utils.py", line 189, in find
    match = cv2.matchTemplate(screen, template, cv2.TM_CCOEFF_NORMED)`

PS Thanks for the hard work

**Comment by Egoistically** [comment]
Seems like [this asset](https://github.com/Egoistically/ALAuto/blob/master/assets/menu/drop_ssr.png) ain't being found, make sure it's in your folder.

**Comment by Egoistically** [comment]
Should be fixed https://github.com/Egoistically/ALAuto/commit/43eb8ba4fe4bfc2214faa98576430b802ef88e8e.
