### ISSUE TITLE
bot wont start :ImportError: DLL load failed 

### ISSUE THREAD

**Issue by Muruxror** [Egoistically/ALAuto#74]
Im really a noob in coding, so maybe someone can help me figure out the error.
`C:\Users\hendr.DESKTOP-0HN3OCO\Desktop\ALAuto-master>python ALAuto.py
Traceback (most recent call last):
  File "ALAuto.py", line 4, in <module>
    from modules.combat import CombatModule
  File "C:\Users\hendr.DESKTOP-0HN3OCO\Desktop\ALAuto-master\modules\combat.py", line 4, in <module>
    from util.utils import Region, Utils
  File "C:\Users\hendr.DESKTOP-0HN3OCO\Desktop\ALAuto-master\util\utils.py", line 8, in <module>
    from scipy import spatial
  File "C:\Users\hendr.DESKTOP-0HN3OCO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\spatial\__init__.py", line 96, in <module>
    from .qhull import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

My system laguage is german... the error means: The specified module was not found. (If you can trust google translator)

**Comment by JustShinobi** [comment]
First of all, are you installing requirements.txt without any errors?

**Comment by Muruxror** [comment]
correct

**Comment by JustShinobi** [comment]
seems to me some error related to scipy library, try do a pip install scipy.

**Comment by Egoistically** [comment]
https://www.google.com/search?q=from+.qhull+import+*+ImportError%3A+DLL+load+failed
https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found

**Comment by Muruxror** [comment]
ok, thx now it is `C:\Users\hendr.DESKTOP-0HN3OCO\Desktop\ALAuto-master>python ALAuto.py
Traceback (most recent call last):
  File "ALAuto.py", line 4, in <module>
    from modules.combat import CombatModule
  File "C:\Users\hendr.DESKTOP-0HN3OCO\Desktop\ALAuto-master\modules\combat.py", line 4, in <module>
    from util.utils import Region, Utils
  File "C:\Users\hendr.DESKTOP-0HN3OCO\Desktop\ALAuto-master\util\utils.py", line 8, in <module>
    from scipy import spatial
  File "C:\Users\hendr.DESKTOP-0HN3OCO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._procrustes import procrustes
  File "C:\Users\hendr.DESKTOP-0HN3OCO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\spatial\_procrustes.py", line 11, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "C:\Users\hendr.DESKTOP-0HN3OCO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Users\hendr.DESKTOP-0HN3OCO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\hendr.DESKTOP-0HN3OCO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

**Comment by Egoistically** [comment]
I'm just copy pasting your error on google https://www.google.com/search?q=scipy.linalg+import+_fblas+ImportError%3A+DLL+load+failed, give this a try I guess.

**Comment by Muruxror** [comment]
im gonna try this on my 2nd pc, the second one is not messed up with some shity phyton projekts

**Comment by Muruxror** [comment]
im done with the install, but i dont get what to change in blustacks, where do i have to change the ip other than config.ini?
`C:\Users\hendr\Desktop\ALAuto-master>python ALAuto.py
[2020-01-17 21:29:15] Initializing config module
[2020-01-17 21:29:15] Validating config
[2020-01-17 21:29:15] Starting ALAuto!
cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (10061)
* daemon not running; starting now at tcp:5037
* daemon started successfully
[2020-01-17 21:29:24] Unable to connect to the service.`

**Comment by Egoistically** [comment]
Do you have adb enabled on Bluestacks?

**Comment by Muruxror** [comment]
enabled it now, everything is working now, thank you so much for the fast and good help.

i guess the fault was the messed up phyton files and the not fitting PATH values.

should i close the issue now?

**Comment by Egoistically** [comment]
No problem! As you wish.
