### ISSUE TITLE
How can i get the traceback?

### ISSUE THREAD

**Issue by latot** [Egoistically/ALAuto#80]
Hi, i would appreciate if is possible add this to the wiki, i try get tracebacks but the logs files have always the same content.....
```
Traceback (most recent call last):
  File "ALAuto.py", line 219, in <module>
    script.run_sortie_cycle()
  File "ALAuto.py", line 79, in run_sortie_cycle
    self.run_event_cycle()
  File "ALAuto.py", line 148, in run_event_cycle
    self.modules['event'].event_logic_wrapper()
  File "C:\Users\User\Documents\Git\ALAuto\modules\event.py", line 84, in event_logic_wrapper
    self.combat_handler()
  File "C:\Users\User\Documents\Git\ALAuto\modules\event.py", line 126, in combat_handler
    Utils.wait_update_screen(1)
  File "C:\Users\User\Documents\Git\ALAuto\util\utils.py", line 98, in wait_update_screen
    cls.script_sleep(time)
  File "C:\Users\User\Documents\Git\ALAuto\util\utils.py", line 70, in script_sleep
    time.sleep(uniform(base, base + flex))
KeyboardInterrupt
```

Maybe this need to be closed in a specific way? (i use ctlr+z)

Bye

**Comment by Egoistically** [comment]
What do you expect to see there other than a traceback?

**Comment by latot** [comment]
mm, when i have a problem before...., when the app stalled i opened a issue, and then i was requested for the traceback, so i think it would have some useful info more than i close the app with ctlr+z...?

Or that traceback is right?

**Comment by Egoistically** [comment]
The traceback is useful for really specific stuff, for the bot getting stuck or things like that just take a screenshot of both the console (bot) log and the emulator (azur lane).

**Comment by latot** [comment]
Okis!

Maybe include this in the wiki, like, with type of bugs and where get the info.

Thx!
