### ISSUE TITLE
ImportError: DLL Load failed

### ISSUE THREAD

**Issue by ghost** [Egoistically/ALAuto#87]
Recently got a new device and keep getting this error,

Traceback (most recent call last):
  File "ALAuto.py", line 5, in <module>
    from modules.combat import CombatModule
  File "C:\Users\Sander4000\Downloads\ALAuto-master\ALAuto-master\modules\combat.py", line 4, in <module>
    from util.utils import Region, Utils
  File "C:\Users\Sander4000\Downloads\ALAuto-master\ALAuto-master\util\utils.py", line 8, in <module>
    from scipy import spatial
  File "C:\Users\Sander4000\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\spatial\__init__.py", line 94, in <module>
    from .kdtree import *
  File "C:\Users\Sander4000\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\spatial\kdtree.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\Sander4000\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\sparse\__init__.py", line 229, in <module>
    from .csr import *
  File "C:\Users\Sander4000\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: DLL load failed: The specified module could not be found.

**Comment by JustShinobi** [comment]
you probably did not install the requirements, try to follow the second installation step again, if there is an error, paste the output here.

**Comment by ghost** [comment]
It says the requirements are already satisfied.

**Comment by Egoistically** [comment]
Has nothing to do with ALAuto but rather with your computer missing a DLL file, search the error on google.

**Comment by hjk22** [comment]
Your scipy installation is broken. Try uninstalling and then reinstalling. It could also be that you're missing some visual c++ redist on your pc. Check these issues and see if you can get to the bottom of this.
[https://stackoverflow.com/questions/52299542/from-sparsetools-import-csr-tocsc-csr-tobsr-csr-count-blocks-importerror](https://stackoverflow.com/questions/52299542/from-sparsetools-import-csr-tocsc-csr-tobsr-csr-count-blocks-importerror)

**Comment by ghost** [comment]
Yeah it was because i didn't have C++ redist on my pc yet. Thanks guys.

**Comment by Egoistically** [comment]
Glad it worked!
